version: '3.7'
services:
  SearchApi:
      image: search-api:latest
      environment:
        POSTGRES_HOST: postgredb
      expose:
      - "80"
  nginx:
      image: nginx:latest
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
      - SearchApi
      ports:
      - "4000:4000"
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432